import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import worker from '../server/chess-relay/credentials-worker.mjs';
const env = { TURN_HOST: 'turn.example.com', TURN_SECRET: 'unit-test-only-random-secret' };
const before = Math.floor(Date.now()/1000);
const response = await worker.fetch(new Request('https://relay.example.com/ice'), env);
assert.equal(response.status, 200);
assert.equal(response.headers.get('Cache-Control'), 'no-store');
assert.equal(response.headers.get('Access-Control-Allow-Origin'), 'https://appassets.androidplatform.net');
const body = await response.text();
assert.ok(!body.includes(env.TURN_SECRET));
const ice = JSON.parse(body), relay = ice.find(server=>server.username);
assert.ok(relay.urls.includes('turns:turn.example.com:443?transport=tcp'));
const expiry = Number(relay.username.split(':')[0]);
assert.ok(expiry >= before + 86400 && expiry <= before + 86402);
assert.equal(relay.credential, createHmac('sha1',env.TURN_SECRET).update(relay.username).digest('base64'));
const another = await (await worker.fetch(new Request('https://relay.example.com/ice'),env)).json();
assert.notEqual(another[1].username,relay.username);
assert.equal((await worker.fetch(new Request('https://relay.example.com/ice'),{})).status,503);
assert.equal((await worker.fetch(new Request('https://relay.example.com/ice',{method:'POST'}),env)).status,404);
assert.equal((await worker.fetch(new Request('https://relay.example.com/unknown'),env)).status,404);
console.log('Credential endpoint tests passed: HMAC matches coturn, expiry, unique identity, no shared-secret disclosure, method/config guards.');
